language: php

# PHP versions that should be tested
php:
  - 5.6
  - 7.0
  - 7.1

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# Cache composer for faster builds
cache:
  directories:
    - $HOME/.composer/cache

# Installing project
before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist

# Checking for PSR2 standards violations
# Running unit tests
script:
  - vendor/bin/phpcs --standard=psr2 ./app ./config ./routes
  - vendor/bin/phpunit

# Sending test coverage report to Code Climate
after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != '7.0' && "$TRAVIS_PHP_VERSION" != '7.1' ]]; then
      vendor/bin/test-reporter;
    f

# Heroky deploy settings
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  on:
    php: 7.0
  run:
    - composer require fzaninotto/faker --no-interaction
    - php artisan migrate:refresh --seed --force
    - composer remove fzaninotto/faker --no-interaction
